import = ["~/.config/alacritty/theme/themes/gruvbox_material_hard_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 350
dimensions.lines = 80
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.7
blur = true

[font]
normal.family = "Hack Nerd Font Mono"
size = 29
